[package]
name = "bye-watch"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
lettre = "0.11.15"
reqwest = { version = "0.12.15", features = ["json", "blocking"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
